version: 2

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Build application Docker image
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker buildx create --use
            docker buildx build . --platform linux/arm64,linux/amd64 -t suitespottechnology/mongo-enterprise:latest --push

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: org-global
