name: Build docker image for arch arm64 needed for mac M1

# Trigger github-action when pushed git tag matches:
# digit.digit.digit-arm64,
# for example: 1.0.3-arm64
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-arm64"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      #  Set tag as a var in steps.vars.outputs.tag
      - name: Get latest tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      # Checkout/clone repository based on steps.vars.outputs.tag
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.tag }}

      # Set up platforms/architectures to emulate (arm64)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-mateo:${{ steps.vars.outputs.tag }}
